### ISSUE TITLE
make body font bigger

### ISSUE THREAD

**Issue by alicetragedy** [cloudfleet/cloudfleet-pelican-theme#1]
Currently the font for the body text is set to 12px, it should be a 14 or even 16 to be easily readable.

**Comment by alicetragedy** [comment]
possibly fixed by 6fc884bc59eed24fca152f76fc380458034b53b3 but let's see if it's really big enough :)

**Comment by metakermit** [comment]
Cool, lemme redeploy to see if it changes it...

**Comment by metakermit** [comment]
Worked, thanks a lot! Much easier on the eyes. http://cloudfleet.io/blog
